apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'com.yanzhenjie.andserver'

apply plugin: 'kotlin-kapt'

android {
    namespace 'com.btsplusplus.fowallet'
    compileSdkVersion 35

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    defaultConfig {
        applicationId "org.evrazcoin.app"
        minSdkVersion 23
        targetSdkVersion 35
        versionCode 202009132
        versionName "6.4"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        externalNativeBuild {
            cmake {
                cppFlags ""
            }
        }
        vectorDrawables.useSupportLibrary = true

        //  默认值
        buildConfigField "boolean", "kAppModuleEnableTabMarket", "true"
        buildConfigField "boolean", "kAppModuleEnableTabDebt", "true"
        buildConfigField "boolean", "kAppModuleEnableOTC", "true"
        buildConfigField "boolean", "kAppModuleEnableGateway", "true"
        buildConfigField "boolean", "kAppCheckUpdate", "true"

        buildConfigField "String", "kAppCommunityFaucetAddress", "\"\""
        buildConfigField "String", "kAppConfigFile", "\"fowallet_config.json\""

        //  不区分维度
        flavorDimensions "default"
    }
    productFlavors {
        btspp {
            //  0:iOS企业版 1:AppStore版 10:btspp 20:community(bbf) 100:baichenglian
            buildConfigField "int", "kAppChannelID", "10"
            buildConfigField "boolean", "kUseCommunityFaucet", "false"
            buildConfigField "String", "kAppConfigFile", "\"fowallet_config_btspp.json\""
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        buildConfig true
        viewBinding true
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.google.android.material:material:1.14.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.core:core-ktx:1.10.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    //   for web socket
    implementation 'org.java-websocket:Java-WebSocket:1.3.9'
    implementation 'com.orhanobut:logger:2.2.0'
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    //  for webserver
    implementation 'com.yanzhenjie.andserver:api:2.1.12'
    kapt 'com.yanzhenjie.andserver:processor:2.1.12'
    //  for wallet core
    implementation files('libs/armeabi-v7a.jar')
    implementation files('libs/x86.jar')
    //  for flurry
    //implementation 'com.flurry.android:analytics:11.6.0@aar'
}
